# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 12:21
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=tinymce.models.HTMLField(default='lklkk'),
            preserve_default=False,
        ),
    ]
